# Generated by Django 4.1.7 on 2023-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='profile_type',
        ),
    ]
