# Generated by Django 4.1.7 on 2023-03-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletype',
            old_name='category',
            new_name='type',
        ),
    ]
