# Generated by Django 4.1.7 on 2023-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Orthopedics', 'Orthopedics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('General Surgery', 'General Surgery'), ('Ophthalmology', 'Ophthalmology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Nephrology', 'Nephrology'), ('Oncology', 'Oncology')], max_length=50),
        ),
    ]
