# Generated by Django 4.1.7 on 2023-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientrecord_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='speciality',
            field=models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('General Surgery', 'General Surgery'), ('Ophthalmology', 'Ophthalmology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Nephrology', 'Nephrology'), ('Oncology', 'Oncology')], max_length=50, null=True),
        ),
    ]
