# Generated by Django 4.1.7 on 2023-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientrecord_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='past_history',
            field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
