# Generated by Django 4.1.7 on 2023-03-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_rename_category_profiletype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('speciality', models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('General Surgery', 'General Surgery'), ('Ophthalmology', 'Ophthalmology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Nephrology', 'Nephrology'), ('Oncology', 'Oncology')], max_length=50)),
                ('experience', models.CharField(choices=[('Attending', 'Attending'), ('3rd year Resident', '3rd year Resident'), ('2nd year Resident', '2nd year Resident'), ('1st year Resident', '1st year Resident')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
