# Generated by Django 4.1.7 on 2023-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='employee_id',
        ),
    ]
