# Generated by Django 4.1.7 on 2023-03-28 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 3, 28))),
                ('timeslot', models.IntegerField(choices=[(800, '8:00  - 8:30'), (830, '8:30  - 9:00'), (900, '9:00  - 9:30'), (930, '9:30  - 10:00'), (1000, '10:00 - 10:30'), (1030, '10:30 - 11:00'), (1100, '11:00 - 11:30'), (1130, '11:30 - 12:00'), (1200, '12:00 - 12:30'), (1230, '12:30 - 13:00'), (1400, '14:00 - 14:30'), (1430, '14:30 - 15:00'), (1500, '15:00 - 15:30'), (1530, '15:30 - 16:00'), (1600, '16:00 - 16:30'), (1630, '16:30 - 17:00'), (1700, '17:00 - 17:30'), (1730, '17:30 - 18:00')])),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.schedule'),
        ),
    ]
